name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run test
      run: |
        go test ./...
      env:
        GO111MODULE: on

    # Build new binaries per CI.
    - name: Build binaries
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --snapshot --rm-dist

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: dist/cli-for-windows_windows_amd64
